id = "fortran"
name = "Fortran"
description = "Fortran support for Zed"
version = "0.0.2"
schema_version = 1
authors = [
    "Xavier Maruff <xavier.maruff@outlook.com>",
    "John Makowski <brickcodes@proton.me>",
]
repository = "https://github.com/Xavier-Maruff/zed-fortran"

[language_servers.fortls]
name = "fortls"
language = "Fortran"

[grammars.fortran]
repository = "https://github.com/Xavier-Maruff/tree-sitter-fortran-wasm"
commit = "87f43efa6d40c00d8ceb9831082348fa82f84ac3"
#commit = "1105385cbcfc7cef1a7bb2d22d61c41678bd1409"
